services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  mssql:
    image: masstransit/sqlserver-quartz:latest
    ports:
      - "1433:1433"
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Quartz!DockerP4ss' -Q 'SELECT 1'"
      ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  quartz:
    build:
      context: ./src
      dockerfile: Dockerfile.quartz
    ports:
      - "5009:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__quartz: "Server=tcp:mssql;Database=quartznet;Persist Security Info=False;User ID=sa;Password=Quartz!DockerP4ss;Encrypt=False;TrustServerCertificate=True;"
      RabbitMqTransport__Host: "rabbitmq"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_healthy
