FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ["QuartzService/QuartzService.csproj", "QuartzService/"]
RUN dotnet restore "QuartzService/QuartzService.csproj"

COPY . .
RUN dotnet publish -c Release --no-restore -o /app QuartzService/QuartzService.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS publish

WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "QuartzService.dll"]